### ISSUE TITLE
How it work with SystemTray ?

### ISSUE THREAD

**Issue by loitranit** [freethinkel/tauri-nspopover-plugin#6]
- Thanks you!

**Comment by freethinkel** [comment]
You can take a look and run the example. Or are you interested in the plugin implementation?

**Comment by loitranit** [comment]
Hi, 
Library is broken when I was building the release.
cd example
yarn tauri build 
- cannot open app @freethinkel

**Comment by freethinkel** [comment]
Did you have any errors in the console? In the example, the running application is only shown in the statusbar, try finding a new icon in the statusbar
