### ISSUE TITLE
 Great job ! How can we open it programatically ?

### ISSUE THREAD

**Issue by Yiork** [freethinkel/tauri-nspopover-plugin#7]
Your NsPopover rust implementation is so great ! but is there a way to open it programatically ? to open it on a specific action of the user without having to click on the tray ?

**Comment by freethinkel** [comment]
Thank you! Not yet but I'm thinking about it, and I think that it is possible to implement only for Tauri v2. Probably I will do it on the next week or u can implement yourself, I will gladly accept your PR.

**Comment by Yiork** [comment]
it try to but i'm not yet really advance in rust programming language.

**Comment by freethinkel** [comment]
I'm working on it :)

**Comment by freethinkel** [comment]
I have added these features in the new version [here](https://github.com/freethinkel/tauri-nspopover-plugin/tree/tauri-beta/v2) for tauri version 2
