### ISSUE TITLE
The popover is shaking when we hover the tray icon (Test using the example folder in V2)

### ISSUE THREAD

**Issue by philippetedajo** [freethinkel/tauri-nspopover-plugin#8]
The example folder is not working properly, the popover is shaking when we hover the tray icon 

https://github.com/freethinkel/tauri-nspopover-plugin/assets/49923201/1130ad40-effe-4ddf-9858-0ef18064e1a7

**Comment by freethinkel** [comment]
Unfortunately I could not reproduce this bug, can you check if it still exists in the latest version? Generally it looks like it is a tauri bug

**Comment by Yiork** [comment]
i have the same bug now, even when i clone the project from scratch.
